Project.create(name: "Project 1", status: 0, description: "Description 1")
Project.create(name: "Project 2", status: 1, description: "Description 2")
Project.create(name: "Project 3", status: 2, description: "Description 3")
Project.create(name: "Project 4", status: 3, description: "Description 4")
Project.create(name: "Project 5", status: 4, description: "Description 5")
